In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3],[33,4,3]])
arr

array([[ 1,  2,  3],
       [33,  4,  3]])

In [3]:
arr.dtype

dtype('int32')

In [4]:
arr.size

6

In [5]:
arr.shape

(2, 3)

In [6]:
marr=np.zeros((5,2))
marr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
marr1=np.ones((5,2))
marr1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
array=np.random.rand(20)
array

array([0.42510125, 0.87549433, 0.83234637, 0.55908245, 0.20382366,
       0.32158107, 0.99820886, 0.31716482, 0.09795578, 0.14482093,
       0.11065949, 0.46504571, 0.05933087, 0.40406601, 0.01718749,
       0.35170551, 0.10847679, 0.95429324, 0.62640537, 0.73745969])

In [15]:
space=np.linspace(1,10,20)

In [16]:
space

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

## identity matrix 

In [18]:
iden=np.identity(3)
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
aa=np.arange(100)
aa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [27]:
aa=aa.reshape(2,50)
aa

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [28]:
aa.T

array([[ 0, 50],
       [ 1, 51],
       [ 2, 52],
       [ 3, 53],
       [ 4, 54],
       [ 5, 55],
       [ 6, 56],
       [ 7, 57],
       [ 8, 58],
       [ 9, 59],
       [10, 60],
       [11, 61],
       [12, 62],
       [13, 63],
       [14, 64],
       [15, 65],
       [16, 66],
       [17, 67],
       [18, 68],
       [19, 69],
       [20, 70],
       [21, 71],
       [22, 72],
       [23, 73],
       [24, 74],
       [25, 75],
       [26, 76],
       [27, 77],
       [28, 78],
       [29, 79],
       [30, 80],
       [31, 81],
       [32, 82],
       [33, 83],
       [34, 84],
       [35, 85],
       [36, 86],
       [37, 87],
       [38, 88],
       [39, 89],
       [40, 90],
       [41, 91],
       [42, 92],
       [43, 93],
       [44, 94],
       [45, 95],
       [46, 96],
       [47, 97],
       [48, 98],
       [49, 99]])

In [29]:
aa.size

100

In [42]:
aa.shape

(2, 50)

In [30]:
aa.ndim

2

In [31]:
aa.nbytes

400

In [32]:
aa.argmax()

99

In [33]:
aa.argmin()

0

In [34]:
aa.argsort()

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49]], dtype=int64)

In [38]:
one=np.array([3,2,5,3,5,7,4,7,9,5])

In [39]:
one.argmax()

8

In [40]:
one.argmin()

1

In [41]:
one.argsort()

array([1, 0, 3, 6, 2, 4, 9, 5, 7, 8], dtype=int64)

In [48]:
ar=np.array([[1,2,3],[4,5,6],[7,1,0]])

In [49]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [52]:
ar2=np.array([[1, 2, 1],
       [4, 3, 2],
       [6, 1, 0]])

In [53]:
ar2

array([[1, 2, 1],
       [4, 3, 2],
       [6, 1, 0]])

In [54]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  8,  8],
       [13,  2,  0]])

In [57]:
ar*ar2 #not matrix multiplication

array([[ 1,  4,  3],
       [16, 15, 12],
       [42,  1,  0]])

In [58]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [61]:
np.count_nonzero(ar)

8

In [62]:
ar.size

9

In [64]:
ar.flags #info about memory layout

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False